CR-899 Added support for Household-Information page
ONSdigital/census-rh-performance-test pull request #14
Opened 2020-12-02 11:37 UTC by PeterBochel

Updating Locust script to support the latest RHUI:

- Following 'request a new access code' link, other enter-postcode page fails.
- Now expects and handles the Household-Information page.

2020-12-09 16:01 UTC, rpcatling requested changes
Only one actually (minor) error spotted.
There are lots of code-style issues (if you open it in pycharm), but consider fixing these on the next iteration:
- initialising all self variables in the class __init__ method  before use (consider an intermediate class of SequentialTaskSet to do this.
- remove TaskSet import (not used)
- some variables shadowing higher level variables (eg id and task) . consider renaming these to identity and taskset
- some long lines could be shortened.
- move all method and class comments below the method / class signature

Let pycharm be your guide if you do the tidy up exercise.

2020-12-09 16:01 UTC, rpcatling commented on locust_tasks/locustfile.py
> +            verify_response('RequestUacSms-6-Household', self, response, 200, Page.SELECT_METHOD)
The identity probably wanted to be 'RequestUacPost-6-Household' here. copy and paste error from the SMS stuff ?

2020-12-18 17:28 UTC, PeterBochel commented on locust_tasks/locustfile.py
> +            verify_response('RequestUacSms-6-Household', self, response, 200, Page.SELECT_METHOD)
Typo fixed.
Have moved initialisation code into an on_start method.
Can't get too excited about pycharm (perf test lifetime too short to pay back the investment)

2020-12-21 16:13 UTC, rpcatling approved these changes

2020-12-21 16:14 UTC, rpcatling commented on locust_tasks/locustfile.py
> +            verify_response('RequestUacSms-6-Household', self, response, 200, Page.SELECT_METHOD)
Not sure I agree with you about pycharm, but won't stop approval.

2021-01-07 14:59 UTC, cookel2 approved these changes
Looks good to me

2021-01-07 15:13 UTC, merged